// Constants

var BASE_URL = "YOUR_BASE_URL";
var BASE_URL_AUTHENTICATION = BASE_URL + "authentication/";

export const Constants = {
  ABOUT_US_URL : "YOUR_ABOUT_US_URL",

  SIGN_UP:BASE_URL_AUTHENTICATION + 'registration',
  LOGIN:BASE_URL_AUTHENTICATION + 'login',
  FORGOTPASSWORD:BASE_URL_AUTHENTICATION + 'ForgotPassword',
  UPDATE_PROFILE:BASE_URL_AUTHENTICATION + 'update_profile',
  USER_DETAIL:BASE_URL_AUTHENTICATION + 'user_info',
  CHANGE_PASSWORD:BASE_URL_AUTHENTICATION + 'changePassword',

}
